[project]
name = "csp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ortools>=9.14.6206",
    "plotly>=6.3.1",
    "pyvista>=0.46.3",
    "rich>=14.2.0",
    "typer>=0.19.2",
    "vedo>=2025.5.4",
]
